config/routes.rb
class OrganizationSubdomain
  def self.matches? request
    case request.subdomain
    when 'www'
      false
    when ''
      false
    else
      true
    end
  end
end

Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#index'

  resources :organizations

  constraints(OrganizationSubdomain) do
    root to: 'contacts#index'
    resources :contacts
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :acls

  has_many :organizations, through: :acls
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ApiBaseController
  # Creates User.
  # Create a user for authenticated account.
  # == Example Request
  # curl -i -H "Authorization: Token token=7LGWItoVYJmjCAMbdRHTSAtt" -X POST -d "user[name]=API User" -d "user[email]=email@api.com" -d "user[tag_list]= tester, new user" -d "attributes[phone]=+123456456" -d "attributes[custom_key]=custom_value" http://localhost:3000/api/v1/users
  # == Request Type:
  # POST
  # == Parameters:
  # [String] user[email] User's email (required)
  # [String] user[name] User's name (optional)
  # [String] user[tag_list] User's tags (optional)
  # [String] attributes[key] User's attributes (optional)
  def create
    user = @api_account.users.new(user_params)
    if user.save
      if params[:attributes].present?
        params[:attributes].keys.each do |key|
          user.user_attributes.create(key: key, value: params[:attributes][key])
        end
      end
      render json: {
          user: user.attributes.merge(tags: user.tag_list, atributes: user.user_attributes.pluck(:key, :value) )
      }, status: 200
    else
      render json: { errors: user.errors.messages }, status: 422
    end
  end

  def add_tags
    user = @api_account.users.find_or_create_by(email: params[:email])

    unless params[:tags].present?
      render json: { errors: ['tag param is missing'] }, status: 422
      return
    end

    user.tag_list = user.tag_list + params[:tags].split(',')

    user.save!

    render json: { user: user.reload }, status: 200
  end

  def remove_tags
    user = @api_account.users.find_or_create_by(email: params[:email])

    unless params[:tags].present?
      render json: { errors: ['tag param is missing'] }, status: 422
      return
    end

    user.tag_list = user.tag_list - params[:tags].split(',')

    user.save!

    render json: { user: user.reload }, status: 200
  end

  # Requiered Paramaters for create a User
  def user_params
    params.require(:user).permit(:name, :email, :tag_list)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_all_tags, only: [:new, :import]

  def index
    @q = current_account.users.includes(:user_attributes, :campaigns, :campaign_users, :tags)
             .ransack(params[:q])
    @q.build_grouping unless @q.groupings.any?
    @q.sorts = 'created_at DESC' if @q.sorts.empty?

    @users = ransack_results_with_limit
    @associations = [:tags, :user_attributes, :campaign_users, :campaign_users_tags, :campaigns, :campaigns_tags]
    @total_user_count = @users.total_count

    @user_attribute_keys = UserAttribute.joins(:user).where('users.account_id = ?', current_account.id).distinct.pluck(:key)

    respond_to do |format|
      format.html
      format.xlsx { render xlsx: 'download', filename: "Users-#{Time.now.strftime("%Y%m%d%H%M")}.xlsx", locals: { users: users_to_export } }
      format.csv { send_data  users_to_export.to_csv_file, filename: "Users-#{Time.now.strftime("%Y%m%d%H%M")}.csv" }
    end
  end

  def detailed_list
    index
  end

  def new; end

  def import; end

  def show
    @user = current_account.users.find(params[:id])
  end

  def create
    if params[:file].present? && params[:tags].present?

      name = "#{(0...50).map { ('a'..'z').to_a[rand(26)] }.join}-#{params[:file].original_filename}"
      directory = 'public/upload'
      path = File.join(directory, name)
      File.open(path, 'wb') { |f| f.write(params[:file].read) }

      ImportUsersJob.perform_later(current_account.id, name, params[:tags])

      @result = 'Your user list importing in background. It will take awhile.'
    else
      @result = { imported_users: 0, import_errors: 'Tags and Csv file required.' }
    end
    redirect_to import_users_path, notice: @result
  end

  def create_single
    user = current_account.users.new(name: params[:name], email: params[:email])
    user.tag_list << params[:tags]
    if user.save
      @result = 'User was successfully created!'
    else
      @result = user.errors.full_messages.to_sentence
    end
    redirect_to new_user_path, notice: @result
  end

  def destroy
    @user = current_account.users.find params[:id]
    @user.user_attributes.destroy_all
    @user.destroy
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_advanced_search.html.haml
= search_form_for @q, html: { method: :get }  do |f|

  = f.grouping_fields do |g|
    = render 'grouping_fields', :f => g

  %p
    = link_to_add_fields "Add Search Grouping", f, :grouping

  .field.actions
    Limit:
    = number_field_tag 'limit_count', params[:limit_count]
  .field.actions
    Sort:
    = f.sort_fields do |s|
      = s.sort_select

  .actions
    = f.submit "Search", class: 'btn btn-primary'

app/views/users/_condition_fields.html.haml
.field
  = f.attribute_fields do |a|
    = a.attribute_select associations: [:campaigns, :tags, :campaign_users, :user_attributes]
  = f.predicate_select

  = f.value_fields do |v|
    = render 'value_fields', f: v

  = link_to_add_fields('Add Field', f, :value)
  = " - "
  = link_to "Remove Fields", '#', class: "remove_fields"

app/views/users/_create_campaign_buttons.html.haml
- if params[:q].present?
  .pull-left
    = link_to new_campaign_path({ q: (params[:q].present? ? params[:q].permit! : 'all'), limit: params[:limit_count] }), class: 'btn btn-primary' do
      %i.fa.fa-plus
      = "Create new campaign for"
      %span.label.label-success= @total_user_count
      = "users"

    - if current_account.campaigns.count > 0
      OR
      &nbsp;

  - if current_account.campaigns.count > 0
    = form_tag add_users_campaigns_path, method: :post, class: 'form-inline' do

      .form-group
        = hidden_field_tag 'filter', (params[:q].presence || {}).to_json
        = hidden_field_tag 'limit', params[:limit_count]
        = select_tag 'campaign_id', options_for_select(current_account.campaigns.map{ |c| [c.name, c.id] }, nil), class: 'form-control'

      = button_tag class: 'btn btn-primary btn-mid', type: :submit do
        %i.fa.fa-arrow-circle-right
        = "Add"
        %span.label.label-success= @total_user_count
        = "users to selected campaign"

app/views/users/_export_buttons.html.haml
= content_for :extra_buttons_in_search do
  = link_to (request.fullpath + '?&format=csv'), class: 'btn btn-default' do
    %i.fa.fa-external-link
    Export to CSV
  = link_to (request.fullpath + '?&format=xlsx'), class: 'btn btn-default' do
    %i.fa.fa-external-link
    Export to Excel

app/views/users/_grouping_fields.html.haml
.group-fields{ 'data-object-name' => f.object_name }
  %p
    = f.combinator_select

  .filters

    = f.condition_fields do |c|
      = render 'condition_fields', f: c

    %p
      = link_to_add_fields "Add Search Condition", f, :condition

app/views/users/_user_search.html.haml
= search_form_for @q do |f|
  %table.table.table-condensed.table-bordered
    %tbody
      %tr
        %td
          %table.table.table-condensed.table-hover.table-bordered
            %tbody
              %tr
                %td= f.label :name_cont
                %td= f.search_field :name_cont, class: 'form-control'
              %tr
                %td= f.label :user_attributes_key_eq
                %td= f.search_field :user_attributes_key_eq, class: 'form-control'
              %tr
                %td= f.label :user_attributes_value_eq
                %td= f.search_field :user_attributes_value_eq, class: 'form-control'
              %tr
                %td= f.label :email_cont
                %td= f.search_field :email_cont, class: 'form-control'
              %tr
                %td= f.label :tags_name_in
                %td= f.select :tags_name_in, options_for_select(@all_tags.pluck(:name).map{ |t| [t.humanize, t] }, @q.tags_name_in), {}, { class: 'select2', multiple: true, include_blank: true }
              %tr
              %tr
                %td= f.label :campaigns_name_in
                %td= f.select :campaigns_name_in, options_for_select(current_account.campaigns.pluck(:name).map{ |c| [c.humanize, c] }, @q.campaigns_name_in), {}, { class: 'select2', multiple: true, include_blank: true }
              %tr
                %td= f.label :campaign_tags_name_in
                %td= f.select :campaigns_tags_name_in, options_for_select(@all_tags.pluck(:name).map{ |t| [t.humanize, t] }, @q.campaigns_tags_name_in), {}, { class: 'select2', multiple: true, include_blank: true }
              %tr
                %td= f.label :campaign_email_status_eq
                -# %td= f.select :campaign_users_status_in, options_for_select(CampaignUser.statuses, @q.campaign_users_status_eq), { include_blank: true }, { class: 'form-control' }
                %td= f.select :campaign_users_status_in, options_for_select(CampaignUser.statuses.map{ |s| [s.first.humanize, s.last] }, @q.campaign_users_status_in), {}, { class: 'select2', multiple: true, include_blank: true }
              %tr
                %td
                  %b Filter Limit
                  %small (Maximum users count)
                %td= number_field_tag 'limit_count', params[:limit_count], class: 'form-control'
              %tr
                %td= f.label :created_at_greater_than
                %td= f.date_field :created_at_gt, class: 'form-control'
              %tr
                %td= f.label :email_sent_at_greater_than
                %td= f.date_field :campaign_users_sent_at_gt, class: 'form-control'
          Grouping Combinator:
          .btn= f.select :m, options_for_select(%w(and or).map{ |ps| [ps, ps] }, @q.m), include_blank: false

  = f.submit "Search", class: 'btn btn-info'
  = link_to 'Clear', users_path, class: 'btn btn-warning actions'

app/views/users/destroy.js.erb
$("#user-<%= @user.id %>").remove();

app/views/users/detailed_list.html.haml
= render 'users/export_buttons'
= page_title 'Detailed Users'

= content_for :page_title_right do
  = link_to new_user_path do
    %button.btn.btn-primary
      %span.fa.fa-plus
      New User

.clearfix

.row
  .col-md-12
    .x_panel
      .x_content
        = render partial: 'shared/advanced_search', locals: { form_url: detailed_list_users_path }
        = render 'create_campaign_buttons'

        = paginate @users

        %table.table.table-striped.table-bordered.table-hover.large-data-table
          %thead
            %tr
              %th{width: "200"} Email
              %th{width: "200"} Tags
              %th Name
              %th Campaigns
              - @user_attribute_keys.each do |key|
                %th= key
              %th{width: "100"}
          %tbody
            - @users.each do |user|
              %tr{id: "user-#{user.id}"}
                %td= user.email
                %td
                  %div{id: "UserTags-#{user.id}"}
                    = render partial: 'tags/item_tags', locals: { item: user }
                %td= user.name
                %td
                  - user.campaigns.each do |cp|
                    = link_to "##{cp.id},", campaign_path(cp), 'data-toggle': 'tooltip', 'data-placement': 'top', 'data-original-title': "#{cp.name}"
                - @user_attribute_keys.each do |key|
                  %td= user.user_attributes.to_a.select{ |ua| ua.key == key }.first.try(:value)

                %td
                  = link_to user_path(user), class: 'btn btn-danger btn-xs', method: :delete, remote: true, data: { confirm: 'Are you sure?' } do
                    %i.fa.fa-trash-o

                  = link_to user_path(user), class: 'btn btn-default btn-xs' do
                    %i.fa.fa-eye

        = paginate @users

app/views/users/import.html.haml
= page_title 'Import Users From File'
= content_for :page_title_right do
  = link_to new_user_path do
    %button.btn.btn-primary
      %span.fa.fa-plus
      New User

.x_panel
  = form_tag users_path, method: :post, multipart: true do

    = label_tag 'File'
    = file_field_tag :file, class: 'form-control'

    = label_tag 'Tags'
    = select_tag :tags, options_for_select(@all_tags.map{ |t| [t, t] }), { include_blank: false, class: 'select2', multiple: true }
    .actions
      = submit_tag 'Import User List', class: 'btn btn-primary'

.col-sm-12
  Example users csv
  %a{href: '/UserList1.csv'} list

app/views/users/index.html.haml
= render 'users/export_buttons'
= page_title 'Users'

= content_for :page_title_right do
  = link_to new_user_path do
    %button.btn.btn-primary
      %span.fa.fa-plus
      New User

.row
  .col-md-12
    .x_panel
      .x_content
        = render partial: 'shared/advanced_search', locals: { form_url: nil }

        = render 'create_campaign_buttons'

        = paginate @users

        %table.table.table-striped.table-bordered.table-hover
          %thead
            %tr
              %th{width: "200"} Email
              %th{width: "200"} Tags
              %th Name
              %th Campaigns
              %th Attributes
              %th.text-center{width: "80"} #
          %tbody
            - @users.each do |user|
              %tr{id: "user-#{user.id}"}
                %td= user.email
                %td
                  %div{id: "UserTags-#{user.id}"}
                    = render partial: 'tags/item_tags', locals: { item: user }
                %td= user.name
                %td
                  - user.campaigns.each do |cp|
                    = link_to "##{cp.id},", campaign_path(cp), 'data-toggle': 'tooltip', 'data-placement': 'top', 'data-original-title': "#{cp.name}"
                %td
                  = render partial: 'user_attributes/index', locals: { user: user }
                %td.text-center= source_action_icons(user, ['show', 'destroy', 'remote']).html_safe

        = paginate @users

app/views/users/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Email</Data></Cell>
        <% @user_attribute_keys.each do |atr| %>
          <Cell><Data ss:Type="String"><%= atr %></Data></Cell>
        <% end %>
        <Cell><Data ss:Type="String">Price</Data></Cell>
      </Row>
      <% @users.each do |user| %>
          <Row>
            <Cell><Data ss:Type="String"><%= user.name %></Data></Cell>
            <Cell><Data ss:Type="String"><%= user.email %></Data></Cell>
            <% @user_attribute_keys.each do |key| %>
              <Cell><Data ss:Type="String"><%= user.user_attributes.select{ |ua| ua.key == key }.first.try(:value) %></Data></Cell>
            <% end %>
          </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/users/new.html.haml
= page_title 'New User'
.row
  .col-sm-8
    .x_panel
      = form_tag create_single_users_path, id: 'single-user', method: :post do

        = label_tag 'Name (optional)'
        = text_field_tag :name, nil, { class: 'form-control' }

        = label_tag 'Email'
        = email_field_tag :email, nil, { class: 'form-control', required: true }

        = label_tag 'Tags'
        = select_tag :tags, options_for_select(@all_tags.map{ |t| [t, t] }), { include_blank: false, class: 'select2', multiple: true }
        .actions
          .pull-right
            = submit_tag 'Save', class: 'btn btn-primary'

  .col-sm-4
    = link_to 'Import Users From CSV or XLS files', import_users_path, class: 'btn btn-default'
    %button.btn.btn-default{"data-target" => ".bs-api-modal-sm", "data-toggle" => "modal", :type => "button"} Create Users Over API

.modal.fade.bs-api-modal-sm{"aria-hidden" => "true", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel2.modal-title Create Users Over API
      .modal-body
        %h4
          Your authentication token:
          %mark= current_account.authentication_token
        %h4
          %mark.text-success POST /api/v1/users
        %h4 Parameters:
        %p String: user[email] -> required. Example: test@example.com
        %p String: user[name] -> optional. Example: Api User
        %p String: user[tag_list] -> optional. Example: new tag, api-users, campaigns
        %p String: attribute[custom_data_key] -> optional. Example: attribute[phone]: +11234543, attribute[location]: USA
        %h4
          Example Request:
        %mark.text-danger
          curl -i -H "Authorization: Token token=
          = current_account.authentication_token
          " -X POST -d "user[name]=API User" -d "user[email]=email@api.com" -d "user[tag_list]= tester, new user" -d "attributes[phone]=+123456456" -d "attributes[custom_key]=custom_value"
          = "#{request.base_url}/api/v1/users"

app/views/users/show.html.haml
.page-title
  .title_left
    %h1= @user.email

.clearfix

.row
  .col-sm-6
    .x_panel
      .x_title
        %h3 Attributes
      .x_content
        = render partial: 'user_attributes/index', locals: { user: @user }

  .col-sm-6
    .x_panel
      .x_title
        %h3 Campaigns
      .x_content
        = render partial: 'campaign_users/index', locals: { user: @user }