config/routes.rb
class OrganizationSubdomain
  def self.matches? request
    case request.subdomain
    when 'www'
      false
    when ''
      false
    else
      true
    end
  end
end

Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#index'

  resources :organizations

  constraints(OrganizationSubdomain) do
    root to: 'contacts#index'
    resources :contacts
  end
end

app/models/organization.rb
class Organization < ApplicationRecord
  after_create :create_tenant

  has_many :acls

  has_many :users, through: :acls

  validates_presence_of :name, :subdomain

  validates_uniqueness_of :subdomain

  def create_tenant
    Apartment::Tenant.create(subdomain)
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  def index
    @organizations = current_user.organizations
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new(organization_params)

    @organization.acls = [Acl.new(role: Role.find_by(identifier: 'owner'), user: current_user)]

    if @organization.save
      redirect_to contacts_url(subdomain: @organization.subdomain)
    else
      render :new
    end
  end

  def organization_params
    params.require(:organization).permit(:name, :subdomain)
  end
end

app/views/organizations/index.html.erb
<% @organizations.each do |org| %>
  <h1><%= org.name %></h1>
<% end %>


<%= link_to 'New Org', new_organization_path %>

app/views/organizations/new.html.erb
<%= form_for @organization do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :subdomain %>
  <%= f.text_field :subdomain %>
  <%= f.submit %>
<% end %>